default: &default
  adapter: postgresql
  port: 5432
  host: localhost
  user: postgres
  password: postgres

development:
  <<: *default
  database: AskApp_development

test:
  <<: *default
  database: AskApp_test

production:
  <<: *default
  database: AskApp_production
  username: AskApp
  password: <%= ENV["ASKAPP_DATABASE_PASSWORD"] %>
